---
title: "Data visualisation"
author: "Ajenthen G. Ranjan"
date: "6/17/2021"
output: html_document
---

```{r setup, include=FALSE}
#load package
source(here::here("R/package-loading.R"))

#load the tidy dataset
load(here::here("data/nhanes_small.rda"))

```

# One variable plots
```{r continuous-variables %>% }

ggplot(nhanes_small, aes(x = bmi)) +
    geom_density()

ggplot(nhanes_small, aes(x= bmi)) + 
    geom_histogram()

```
```{r discrete-variables}

ggplot(nhanes_small, aes(x = sex)) + 
    geom_bar()

ggplot(nhanes_small, aes(x = diabetes)) + 
    geom_bar()


```

```{r remove-missing-diabetes}

nhanes_tidied <- nhanes_small %>% 
    filter(!is.na(diabetes))

usethis::use_data(nhanes_tidied, overwrite = TRUE)

ggplot(nhanes_tidied, aes(x = diabetes)) + 
    geom_bar()

```

# Plotting two variables

```{r continuous-two-variables}
bmi_chol <- ggplot(nhanes_tidied, aes(x = bmi, y = tot_chol))
    
bmi_chol +
    geom_point()

bmi_chol +
    geom_hex()

bmi_chol + 
    geom_smooth()


bmi_chol + 
    geom_point() +
    geom_smooth()

bmi_chol + 
    geom_hex() +
    geom_smooth()
```

```{r 2-discrete-variables}
two_discrete <- nhanes_tidied %>% 
    ggplot(aes(x = diabetes, fill = sex))

two_discrete + 
    geom_bar()

two_discrete + 
    geom_bar(position = position_dodge())
    

```

```{r discrete-continuous-variable}

two_mixed <- nhanes_tidied %>% 
    ggplot(aes(x = diabetes, y = bmi))

two_mixed + 
        geom_boxplot()

two_mixed + 
        geom_jitter()

two_mixed +
    geom_violin()


```

# Exercise to make plots with one or two variables

```{r}
# 1a. Distribution of age
ggplot(nhanes_tidied, aes(x = age)) +
    geom_histogram()


# 1b. Distribution of age of diabetes diagnosis
ggplot(nhanes_tidied, aes(x = diabetes_age)) +
    geom_histogram()

# 2a. Number of people who smoke now
ggplot(nhanes_tidied, aes(x = smoke_now)) +
    geom_bar()

# 2b. Number of people who are physically active
ggplot(nhanes_tidied, aes(x = phys_active)) +
    geom_bar()

# 3a. BMI in relation to systolic blood pressure
ggplot(nhanes_tidied, aes(x = bmi, y = bp_sys_ave)) +
    geom_hex()

# 3b. BMI relation to diastolic blood pressure
ggplot(nhanes_tidied, aes(x = bmi, y = bp_dia_ave)) +
    geom_hex()
    
# 4. Physically active people with or without diabetes
ggplot(nhanes_tidied, aes(x = diabetes, fill = phys_active)) +
    geom_bar(position = position_dodge())

# 5. Poverty levels between those with or without diabetes
ggplot(nhanes_tidied, aes(x = diabetes, y = poverty)) +
    geom_violin()

```
# Plotting three or more variables

```{r using-colour}
## Plot systolic blood pressure in relation to sex and diabetes status
nhanes_tidied %>% 
    ggplot(aes(x = sex, y = bp_sys_ave, colour = diabetes)) +
    geom_boxplot()


## Plot BMI in relation to systolic blood pressure and age
nhanes_tidied %>%
    ggplot(aes(x = bmi, y = bp_sys_ave, colour = age)) +
    geom_point()

## Plot BMI in relation to systolic blood pressure and diabetes status
nhanes_tidied %>% 
    ggplot(aes(x = bmi, y = bp_sys_ave, colour = diabetes)) +
    geom_point()

```
```{r using-facetting function}
## Plot BMI in relation to systolic blood pressure and diabetes status using
### faceting by column - side by side
nhanes_tidied %>% 
    ggplot(aes(x = bmi, y = bp_sys_ave)) +
    geom_point() +
    facet_grid(cols = vars(diabetes))

### faceting by row - Stacked
nhanes_tidied %>% 
    ggplot(aes(x = bmi, y = bp_sys_ave)) +
    geom_point() +
    facet_grid(rows = vars(diabetes))

### faceting by row and columns
nhanes_tidied %>% 
    ggplot(aes(x = bmi, y = bp_sys_ave)) +
    geom_point() +
    facet_grid(cols = vars(sex), rows = vars(diabetes))

### faceting by row and columns with colours
nhanes_tidied %>% 
    ggplot(aes(x = bmi, y = bp_sys_ave
           , colour = age)) +
    geom_point() +
    facet_grid(cols = vars(sex), rows = vars(diabetes))



```

#changing colours
```{r viridis}
# Barplot to work from, with two discrete variables
base_barplot <- nhanes_tidied %>% 
    ggplot(aes(x = diabetes, fill = sex)) +
    geom_bar(position = position_dodge())

base_barplot +
    scale_fill_viridis_d(option = "A")

# Scatterplot to work from, with three continuous variables
base_scatterplot <- nhanes_tidied %>% 
    ggplot(aes(x = bmi, y = bp_sys_ave, colour = age)) +
    geom_point()

base_scatterplot +
scale_color_viridis_c(option = "A")

```

#Changing plot appearence
```{r built-in-themes}

## Create scatterplot to play with themes
base_scatterplot2 <- base_scatterplot +
    facet_grid(rows = vars(diabetes),
               cols = vars(sex)) +
    scale_color_viridis_c(option = "G")

## View the plot with the default theme
base_scatterplot2

## Try different theme
base_scatterplot2 + 
        theme_minimal()


###SET THE THEME FOR ALL PLOTS
theme_set(theme_minimal())

## Change title and labels
base_scatterplot3 <-base_scatterplot2 +
    labs(title = "The relationship of BMI, systolic blood pressure and age stratified by sex",
         x = "BMI (kg/m2)",
         y = "Systolic blood pressure (mmHg)")
```

# Saving the plot
```{r}
ggsave(here::here("doc/images/scatterplot.pdf"), 
       base_scatterplot3, width = 7, height = 5)
```

